### ISSUE TITLE
QsciScintilla.text() Issues

### ISSUE THREAD

**Issue by thautwarm** [matkuki/qscintilla_docs#13]
Hello Matic,

Thanks for making this impressive documentation and https://github.com/matkuki/ExCo .

Question:

At [ExCo/lexers/python](https://github.com/matkuki/ExCo/blob/515aaca3b3ee1619b8c79d84ff2ef230a49e3d3a/lexers/python.py#L204)

```python
text = bytearray(editor.text().lower(), "utf-8")[start:end].decode("utf-8")
```

I wonder if there is an API giving us a Python `bytes` or a Python proxy of CXX side bytes used in Scintilla? The current one is quite heavy.

**Comment by thautwarm** [comment]
`.bytes(start, end)`

**Comment by matkuki** [comment]
@thautwarm 
Thanks!
Great that you found the `bytes` API, I think it's a relatively recent addition. When I started with QScintilla, I don't think it was there.

**Comment by thautwarm** [comment]
Yes, it took me quite a few times reading the documentations. With this, we can avoid a redundant copy of the whole text!

Your documentation is extremely useful and well structured, however it seems that fully documenting QScintilla is a quite big thing..
