### ISSUE TITLE
bug report: when load a big text file, such as 30M size . then change into Word wrap mode , Memory crept up to 1.5 gigabytes

### ISSUE THREAD

**Issue by cxasm** [matkuki/qscintilla_docs#15]
when load a big text file, such as 30M size , i see The memory usage is within 400M.

but when i change into word warp mode, Memory crept up to 1.5 gigabytes.

After exiting the wrapping mode, memory can come down。

I found notepad++ no such problem. There should be a memory problem, can  author find it?

**Comment by JakobDev** [comment]
This is a 3rd party documentation project. It has nothing to do with the development of QScintilla. You should report Bug reports [on the official mailing list](https://www.riverbankcomputing.com/mailman/listinfo/qscintillal).

**Comment by matkuki** [comment]
Thank you @JakobDev for responding so fast 👍.
