### ISSUE TITLE
Formatting display of control characters.

### ISSUE THREAD

**Issue by szoshi** [matkuki/qscintilla_docs#17]
I am working on a simple editor using QScintilla and PyQt5. I can replace certain characters using SCI_SETREPRESENTATION (for e.g. I can show '-' instead of a space). However, all control characters are rendered inverted on a black background. I have read in the docs that the function SCI_SETREPRESENTATIONAPPEARANCE can be used to control the appearance but this function is not implemented in the port.

Is there an alternate method to format the display of control characters using QScintilla?

**Comment by matkuki** [comment]
`SCI_SETREPRESENTATIONAPPEARANCE` seems to be available only on newer version of Scintilla.

I have never used this functionality before, but I see what you mean, for example replacing a `space` with a `minus` gives this:
![image](https://github.com/matkuki/qscintilla_docs/assets/10289651/b361c6fe-4e96-4812-8dbf-6adef6995017)

Am investigating this further ...

**Comment by matkuki** [comment]
This seems to be the default behaviour, as I have added a custom `Lexer` to the editor with a dark background and light text colours, and it also reverses the replaced characters with a light background and dark text:
![image](https://github.com/matkuki/qscintilla_docs/assets/10289651/975265be-bc7b-4051-950d-8dd18f6918a6)

**Comment by szoshi** [comment]
Is there any way to change it? It need not apply to all characters. I would be happy if I could show the minus sign in place of a space on a regular background.

**Comment by matkuki** [comment]
@szoshi 
I'm afraid that `QScintilla` is based on an older `Scintilla` version that does not have the `SCI_SETREPRESENTATIONAPPEARANCE` call exposed, as you already found. I downloaded and checked the source code and there is no mention of `SCI_SETREPRESENTATIONAPPEARANCE` anywhere. This can be confirmed by opening the documentation file of the `QScintilla`'s `Scintilla` and you see this:
![image](https://github.com/matkuki/qscintilla_docs/assets/10289651/4b8fef8d-dba1-4caf-ace6-09a5c1bb6ebe)

So sorry, currently I don't think it's possible in `QScintilla`.

**Comment by matkuki** [comment]
Corrention: there is one way, here is a hint (note the color changes of the special `minus` character that replaced all the spaces):
![image](https://github.com/matkuki/qscintilla_docs/assets/10289651/0a9e2687-4ea1-4d66-8243-08328d0d71cb)
You need to create a custom `QsciLexerCustom` then parse all the replacement characters and style them with the inverse color scheme: Paper color is Text color, Text color is Paper color. Then it will work. But it's extra work.

**Comment by szoshi** [comment]
That sounds doable. Thanks for taking the time to review this. I will close this now and open a new issue if necessary.
