### ISSUE TITLE
Wrong PNG in one of the examples on the website

### ISSUE THREAD

**Issue by 8day** [matkuki/qscintilla_docs#2]
At this page (https://qscintilla.com/text-wrapping/) example for `startFlag.WrapFlagInMargin` must use `wrap_visual_flags_3.png` rather than `wrap_visual_flags_0.png`.  Your PDF seems to have no such issue, and most likely it exists only on the website.

P.S. Thank you both for your work. Both docs and website are extremely useful considering how cryptic Scintillla and Qsci are.

**Comment by matkuki** [comment]
Thanks. Will try and fix it as soon as possible.

**Comment by kristofmulier** [comment]
Hi @8day,
Thank you very much for noticing this error. I have corrected the page (https://qscintilla.com/text-wrapping/).
Both Matic and me are happy to receive your kind words of appreciation for our efforts :-)

Kind greetings,

Kristof Mulier
