### ISSUE TITLE
sublime-syntax & .tmTheme support on QScintilla widgets

### ISSUE THREAD

**Issue by brupelo** [matkuki/qscintilla_docs#6]
Hi, how you doing?

I've created a little standalone text editor that uses QScintilla and it supports some textmate features but it's on the very early stage and there is a lot of work to do to get it in shape. I'd need people with real skills like you to share the workload and make it usable, you can read a little bit about it [here](https://forum.sublimetext.com/t/standalone-sublimetext-widget/42065/2), would you like to join?

Yours,
Bruno

**Comment by brupelo** [comment]
[https://github.com/brupelo/pyblime](https://github.com/brupelo/pyblime)

**Comment by matkuki** [comment]
Hey @brupelo 
Excellent work with `pyblime`! I wish you the best of luck.
As for collaborating, sorry but I am already part of a team that is making and IDE and I have absolutely no time for other projects.
If you have issues with QScintilla then I can try to help, but for anything else I am too busy, sorry.

Regards,
Matic

**Comment by brupelo** [comment]
@matkuki Matic, hiya! Sure, I totally understand mate, sounds like the expected answer, thanks anyway ;)

I'm not an expert in the open-source movement but it seems like a really hard job to find contributors for a particular project. Since yesterday I've started to ask by IRC, forums, github issues for help and so far nobody interested/joined yet lol.

About QScintilla issues... for sure, I'll be asking specific stuff about it here and there as I've done in the past... to be honest, from my contacts, you're the one with more knowledge about QScintilla so far hehe. That's why I'd decided to ask explicitely to you ;)

Yours,
Bruno

Ps. Btw, you've talked you're making an IDE... pyblime is mainly intended to use as a component for python pyqt/pyside2 IDEs... I'm also coding some tools where I'd like to replace some "vanilla" QScintillas by pyblime (if it becomes production-ready eventually), just saying... :)

**Comment by matkuki** [comment]
> I'm not an expert in the open-source movement but it seems like a really hard job to find contributors for a particular project.

You have no idea. Most important factor seems to be luck.

> pyblime is mainly intended to use as a component for python pyqt/pyside2 IDEs...

If you can make this work with `pyside2` without external dependencies, I would certainly love to try it.

**Comment by brupelo** [comment]
> You have no idea. Most important factor seems to be luck.

I believe you, as I said, my experience with open-source projects is minimal... but so far I've been posting links everywhere in the past days and so far I've just got 1 potential contributor :) . In any case, I think one of the keys is to make things as simple as possible so potential contributors won't feel very intimidated to get on board... For instance, take a look to this [doc](https://github.com/brupelo/pyblime/blob/master/docs/build.md), to me that's a 20s job... but I'm aware the process described there is not "1 single push button build" so in my book that's just wrong and needs to be improved. Unfortunately, nowadays coders have become lazier and if they feel like they'll waste time trying to setup things they'll give up very soon :) . Young people.... in my times where internet was not a thing we had to reverse engineer stuff with almost no manuals... that was hard!

> If you can make this work with pyside2 without external dependencies, I would certainly love to try it.

Definitely that's something I'd really love to, in fact, I'd opened some issue few days [ago](https://github.com/brupelo/pyblime/issues/10)... It's not like I dislike pyqt... but I definitely would prefer get rid of that dependency and using just pyside2 (not even supporting both... just pyside2!)

Anyway, first thing first... before that happens the widget needs to become production ready (features, speed, usability, ...)

\o

Yours,
Bruno
