### ISSUE TITLE
How to set color to margin line numbers?

### ISSUE THREAD

**Issue by brupelo** [matkuki/qscintilla_docs#7]
First of all, let me tell you I've read the whole [https://qscintilla.com/margins/](https://qscintilla.com/margins/) section from the docs but I still don't understand why I'm not able
to make proper coloring in this issue [Different colors to SublimeText](https://github.com/brupelo/pyblime/issues/1).

Right now I'm hardcoding it to force the same margin color than Sublime using this [statements](https://github.com/brupelo/pyblime/blob/master/pyblime/view.py#L92-L97) but that's been ignored for some reason I don't understand.

Of course, the above is just a test and the margins should eventually be used from the .tmTheme, like [here](https://github.com/brupelo/pyblime/blob/master/pyblime/view.py#L500-L502)

Hopefully you can bring some light to this as I've tried to figure it out for a while already ;)

**Comment by matkuki** [comment]
Ah, the old `why does the folding margin not change colors` problem. The folding margin is special.
You need to use the `setFoldMarginColors` and `resetFoldMarginColors` functions to color it.

As for the indentation guides, use `setIndentationGuidesForegroundColor` and `setIndentationGuidesBackgroundColor`.

I'm not sure why you circled the line margin in the `pyblime` issue, but I'm assuming that the text is too dark? In the code [statements](https://github.com/brupelo/pyblime/blob/master/pyblime/view.py#L92-L97), the foreground color is the text color, while the background color is the margin color. And you're setting the text to a darker color than the margin.

Hope it helps.

**Comment by brupelo** [comment]
@matkuki I've wanted to try your hints since the day you posted your answer but I didn't find the time till today :/ . Anyway, I've spent 1 hour creating a new widget to display the theme colors and one of issues is already solved, the one related with `setFoldMarginColors` and `resetFoldMarginColors`... now I still need to figure out the ones related with the indentation guides as well as the one related with the margin font colors... You can see a new screenshots demo [here](https://github.com/brupelo/pyblime#screenshots).

Anyway, I'll continue sticking to your answer in order to solve the other issues...

> Hope it helps.

Of course it helps! It's a quite unfortunate you don't have extra time to contribute to the widget as your knowledge about Scintilla internals is extremely high and we'd get the job done in no time :/ . I wonder, did you help to Neil Hodgson or Phil Thompson when they coded Scintilla & QScintilla? Or did your knowledge adquired while creating the nice qscintilla.com tutorials?

Anyway... let's figure out the other ones so I can close this one asap.

Ty!

**Comment by brupelo** [comment]
@matkuki Hi again! I've got stuck again with this issue, today I was trying to apply your advices and I don't know what's wrong here, take a look to this part of the [code](https://github.com/brupelo/pyblime/blob/6d5ef485a3adb7ecfb35ecca1d612c6532d75278/pyblime/view.py#L506-L507), I've tried using some hardcoded values there such as:

        self._set_color("setIndentationGuidesBackgroundColor", Color(0, 0, 255, 0))
        self._set_color("setIndentationGuidesForegroundColor", Color(0, 255, 0, 0))

But I don't understand what I'm getting here, look:

![showcase](https://dl.dropboxusercontent.com/s/681ufpdlb2fw9di/python_2019-03-27_10-34-07.png)

Do you have any idea why the blue/green hardcoded colors are being ignored? :/ ... Tsk, fixing the color on text margins and indentation lines would make a big difference to create much better screenshots :D

**Comment by brupelo** [comment]
I think the solution to my problem was using the coloring functions after you've set the lexer, not before. 

I've also noticed some style numbers may be reserved in QScintilla, I didn't find the exact code/docs where that's explained in Scintilla/QScintilla but I've seen this [comment](https://github.com/pycom/EricShort/blob/master/QScintilla/Lexers/LexerPygments.py#L55) in `Eric's` text editor... So in the lexer I won't just use styles [0-7] or [32-39]
